name: Extended Pipeline

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-docker-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup BinaryNinja License
        run: |
          echo "${{ secrets.BINJA_LICENSE }}" | base64 --decode > license.txt
      - name: Download BinayNinja.zip
        run: |
          curl -v --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_BINJA_TOKEN }}" https://gitlab.fkie.fraunhofer.de/api/v4/projects/1250/repository/files/BinaryNinja.zip/raw?ref=main --output BinaryNinja.zip
      - name: Build Docker Image
        run: |
          docker build -t dewolf .
      - name: Run Tests
        run: |
          docker run dewolf make extendedtests
