name: Extended Pipeline

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build-docker-and-run-extended-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup BinaryNinja License
        run: |
          echo "${{ secrets.BINJA_LICENSE }}" | base64 --decode > license.txt
      - name: Download BinayNinja.zip
        run: |
          curl -L --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_BINJA_TOKEN }}" "https://gitlab.fkie.fraunhofer.de/api/v4/projects/1250/repository/archive.zip?sha=Binja5" -o complete_repo.zip
      - name: Build Docker Image
        run: |
          docker build -t dewolf .
      - name: Run Tests
        run: |
          docker run dewolf make extendedtests
