name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download BinayNinja.zip
        run: |
          curl --header "PRIVATE-TOKEN: $GITLAB_BINJA_TOKEN" https://gitlab.cc-asp.fraunhofer.de/api/v4/projects/27455/repository/files/BinaryNinja.zip/raw\?ref\=main --output BinaryNinja.zip
        env:
          GITLAB_BINJA_TOKEN: ${{ secrets.GITLAB_BINJA_TOKEN }}
      - name: Setup BinaryNinja License
        run: |
          echo "$BINJA_LICENSE" > "$(pwd)/license.txt"
        env:
          BINJA_LICENSE: ${{ secrets.BINJA_LICENSE }}
      - name: Build Docker Image
        run: |
          docker build -t dewolf .
          
