name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  BINJA_LICENSE: ${{ secrets.BINJA_LICENSE }}
  GITLAB_BINJA_TOKEN: ${{ secrets.GITLAB_BINJA_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download BinayNinja.zip
        run: |
          curl -v --header "PRIVATE-TOKEN: ${{env.GITLAB_BINJA_TOKEN}}" https://gitlab.cc-asp.fraunhofer.de/api/v4/projects/27455/repository/files/BinaryNinja.zip/raw\?ref\=main --output BinaryNinja.zip
      - name: Setup BinaryNinja License
        run: |
          echo "${{env.BINJA_LICENSE}}" > "$(pwd)/license.txt"
      - name: Build Docker Image
        run: |
          docker build -t dewolf .
          
