name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
        image: fkiedewolf/binja:latest
        credentials:
           username: fkiedewolf
           password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Copy dewolf into Container
        run: |
          cp -r * /opt/decompiler/
      - name: Run Format Check
        run: |
          cd /opt/decompiler && make check-format
      - name: Run Tests
        run: |
          cd /opt/decompiler && make
