name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  run-tests:
    runs-on: fkiedewolf/binja:latest
    container:
        image: ghcr.io/fkiedewolf/binja:latest
        credentials:
           username: fkiedewolf
           password: ${{  secrets.DOCKERHUB_ACCESSTOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup BinaryNinja License
        run: |
          echo "${{ secrets.BINJA_LICENSE }}" | base64 --decode > /root/.binaryninja/license.dat
      - name: Copy dewolf into Container
        run: |
          cp -r * /opt/dewolf/
      - name: Run Format Check
        run: |
          make check-format
      - name: Run Tests
        run: |
          make
